"""Remove profile column

Revision ID: f59ac1c80873
Revises: 26d60b531f57
Create Date: 2025-05-24 14:21:01.596394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59ac1c80873'
down_revision = '26d60b531f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
